In [6]:
import numpy as np 
import pandas as pd 
import pandas_datareader as web
#import pandas.io.data as web 
from pandas_datareader import data, wb
import jqdatasdk as jd
import pandas_datareader.data as web


In [ ]:
sp500= data.DataReader('^GSPC', data_source='yahoo', start='1/1/2000', end='1/12/2017') 
#sp500= data.DataReader('^GSPC', data_source='yahoo') 
sp500.ix['2010-01-04'] 
sp500.info() 
print(sp500) 
print(sp500.columns) 
print(sp500.shape)
import matplotlib.pyplot as plt 
plt.plot(sp500['Close'])
# now calculating the 42nd Days and 252 days trend for the index 
sp500['42d']= np.round(pd.rolling().mean(sp500['Close'], window=42),2) 
sp500['252d']= np.round(pd.rolling().mean(sp500['Close'], window=252),2)
#Look at the data 
sp500[['Close','42d','252d']].tail() 
plt.plot(sp500[['Close','42d','252d']])

In [ ]:
import cherrypy

class HelloWorld(object):
    @cherrypy.expose
    def index(self):
        return "Hello World!"

cherrypy.quickstart(HelloWorld())

[25/Jun/2019:11:24:52] ENGINE Listening for SIGTERM.
[25/Jun/2019:11:24:52] ENGINE Listening for SIGHUP.
[25/Jun/2019:11:24:52] ENGINE Listening for SIGUSR1.
[25/Jun/2019:11:24:52] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[25/Jun/2019:11:24:52] ENGINE Started monitor thread 'Autoreloader'.
[25/Jun/2019:11:24:52] ENGINE Serving on http://127.0.0.1:8080
[25/Jun/2019:11:24:52] ENGINE Bus STARTED


In [8]:
from hmmlearn.hmm import GaussianHMM
import numpy as np
from matplotlib import cm, pyplot as plt
import matplotlib.dates as dates
import pandas as pd
import datetime

In [15]:
beginDate = '2005-01-01'
endDate = '2015-12-31'
n = 6 #6个隐藏状态
#data = get_price('CSI300.INDX',start_date=beginDate, end_date=endDate,frequency='1d')
#df = rd.get_price('CSI300.INDX', '2005-01-01', '2015-07-25').reset_index()[['OpeningPx', 'ClosingPx']]
data=jd.get_index_stocks('000300.XSHG',start_date=beginDate, end_date=endDate,frequency='1d')
data = web.DataReader("AMZN","quandl",
                      datetime.datetime(2005,1,1),
                      datetime.datetime(2015,1,1),
                      access_key = 'RGqizhsWNp9P1gM7wx5u'
                     ).sort_index()
data[0:9]

run jqdatasdk.auth first


Open   High    Low  Close      Volume  ExDividend  SplitRatio  \
Date                                                                         
2005-01-03  44.95  45.44  44.21  44.52  10446500.0         0.0         1.0   
2005-01-04  42.62  43.26  41.50  42.14  19418500.0         0.0         1.0   
2005-01-05  41.57  42.76  41.56  41.77   8354200.0         0.0         1.0   
2005-01-06  41.81  42.25  40.90  41.05   8700900.0         0.0         1.0   
2005-01-07  41.33  42.69  41.16  42.32   9836600.0         0.0         1.0   
2005-01-10  42.05  42.96  41.71  41.84   7347900.0         0.0         1.0   
2005-01-11  41.40  42.16  41.01  41.64   7920300.0         0.0         1.0   
2005-01-12  41.49  42.48  40.82  42.30   8072300.0         0.0         1.0   
2005-01-13  42.45  44.58  42.34  42.60  17393600.0         0.0         1.0   

            AdjOpen  AdjHigh  AdjLow  AdjClose   AdjVolume  
Date                                                        
2005-01-03    44.95    45.44   44.21     44.52  10446500.0  
2005-01-04    42.62    43.26   41.50     42.14  19418500.0  
2005-01-05    41.57    42.76   41.56     41.77   8354200.0  
2005-01-06    41.81    42.25   40.90     41.05   8700900.0  
2005-01-07    41.33    42.69   41.16     42.32   9836600.0  
2005-01-10    42.05    42.96   41.71     41.84   7347900.0  
2005-01-11    41.40    42.16   41.01     41.64   7920300.0  
2005-01-12    41.49    42.48   40.82     42.30   8072300.0  
2005-01-13    42.45    44.58   42.34     42.60  17393600.0

In [18]:
#拿到每日成交量和收盘价的数据。
volume = data['Volume']
close = data['Close']

In [20]:
#计算每日最高最低价格的对数差值，作为特征状态的一个指标。
logDel = np.log(np.array(data['High'])) - np.log(np.array(data['Low']))
logDel

array([0.02744177, 0.04153499, 0.02846492, ..., 0.02477376, 0.01476089,
       0.00953474])

In [21]:
#计算每5日的指数对数收益差，作为特征状态的一个指标。
logRet_1 = np.array(np.diff(np.log(close)))#这个作为后面计算收益使用
logRet_5 = np.log(np.array(close[5:])) - np.log(np.array(close[:-5]))
logRet_5

array([-0.06208571, -0.01193616,  0.01260871, ...,  0.0396823 ,
        0.01219132,  0.01318465])

In [23]:
#计算每5日的指数成交量的对数差，作为特征状态的一个指标。
logVol_5 = np.log(np.array(volume[5:])) - np.log(np.array(volume[:-5]))
logVol_5

array([-0.35185244, -0.89679714, -0.03432596, ..., -1.0627487 ,
       -0.64864122, -0.27840746])

In [24]:
#由于计算中出现了以5天为单位的计算，所以要调整特征指标的长度。
logDel = logDel[5:]
logRet_1 = logRet_1[4:]
close = close[5:]
Date = pd.to_datetime(data.index[5:])

In [33]:
#把我们的特征状态合并在一起。
A = np.column_stack([logDel,logRet_5,logVol_5])
A

array([[ 0.02952854, -0.06208571, -0.35185244],
       [ 0.02765596, -0.01193616, -0.89679714],
       [ 0.03986122,  0.01260871, -0.03432596],
       ...,
       [ 0.02477376,  0.0396823 , -1.0627487 ],
       [ 0.01476089,  0.01219132, -0.64864122],
       [ 0.00953474,  0.01318465, -0.27840746]])

In [39]:
#model = GaussianHMM(n_components= n, covariance_type="full", n_iter=2000).fit([A])
model = GaussianHMM(n_components= n, covariance_type="full", n_iter=2000).fit([A])
hidden_states = model.predict(A)
hidden_states

ValueError: Found array with dim 3. Estimator expected <= 2.

 help(GaussianHMM)

In [2]:
import copy
import datetime
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_finance import candlestick_ohlc
import matplotlib.dates as mdates
from matplotlib.dates import (
DateFormatter,WeekdayLocator,DayLocator,MONDAY
)
import numpy as np
import pandas as pd
import pandas_datareader.data as web
from sklearn.cluster import KMeans



start = datetime.datetime(2013,1,1)
end = datetime.datetime(2015,12,31)
sp500 = web.DataReader('CHRIS/CME_SP1','quandl',start,end,access_key = 'RGqizhsWNp9P1gM7wx5u')

#plot_candlesticks(sp500,datetime.datetime(2014,6,1))
data = sp500
since = datetime.datetime(2014,6,1)
df = copy.deepcopy(data)
df = df[df.index >= since]
df.reset_index(inplace = True)

df
# mondays = WeekdayLocator(MONDAY)
# alldays = DayLocator()
# weekFormatter = DateFormatter('%b %d')
# fig,ax = plt.subplots(figsize = (16,4))
# fig.subplots_adjust(bottom = 0.2)
# ax.xaxis.set_major_locator(mondays)
# ax.xaxis.set_minor_locator(alldays)
# ax.xaxis.set_major_formatter(weekFormatter)

# csticks = candlestick_ohlc(ax,df[['date_fmt','Open','High','Low','Last']].values,width = 0.6,
#                            colorup = '#000000',colordown = '#ff0000')
# ax.set_facecolor((1,1,0.9))  
# plt.setp(plt.gca().get_xticklabels(),
#         rotation = 45,horizontalalignment = 'right')
# plt.show()

# sp500_norm = get_open_normalized_prices(sp500)
# k = 5
# km = KMeans(n_clusters = k,random_state = 42)
# km.fit(sp500_norm)
# labels = km.labels_
# sp500['Cluster'] = labels

# #plot_3d_normalized_candles(sp500_norm)
# data = sp500_norm
# fig = plt.figure(figsize = (12,9))
# ax = Axes3D(fig,elev = 21,azim = -136)
# ax.scatter(
#     data['H/O'],data['L/O'],data['C/O'],c = labels.astype(np.float))
# ax.set_xlabel('High/Open')
# ax.set_ylabel('Low/Open')
# ax.set_zlabel('Close/Open')
# plt.show()

Date    Open    High     Low    Last  Change  Settle   Volume  \
0   2015-12-31  2054.5  2057.1  2030.5  2036.5    19.2  2035.4   4211.0   
1   2015-12-30  2072.3  2074.2  2054.0  2054.5    18.2  2054.6   3828.0   
2   2015-12-29  2049.7  2074.0  2048.0  2072.0    24.0  2072.8   8080.0   
3   2015-12-28  2052.4  2053.4  2035.5  2050.5     2.4  2048.8   4504.0   
4   2015-12-24  2052.9  2059.3  2045.0  2045.0     1.8  2051.2    652.0   
5   2015-12-23  2034.2  2057.8  2031.5  2053.0    17.1  2053.0   7422.0   
6   2015-12-22  2020.6  2036.3  2007.8  2036.1    21.0  2035.9   3563.0   
7   2015-12-21  1999.0  2019.0  1995.9  2015.0    23.0  2014.9   1227.0   
8   2015-12-18  2024.0  2028.9  1991.5  1993.0    32.8  1991.9  12732.0   
9   2015-12-17  2078.0  2078.0  2037.0  2037.0    37.8  2034.3   9275.0   
10  2015-12-16  2057.0  2075.5  2042.0  2073.7    26.5  2072.1  16605.0   
11  2015-12-15  2038.5  2053.0  2038.5  2044.0    27.2  2045.6  24781.0   
12  2015-12-14  2012.5  2023.5  1995.5  2019.5     8.6  2018.4  25553.0   
13  2015-12-11  2025.0  2033.4  2008.0  2010.0    39.5  2009.8  34365.0   
14  2015-12-10  2047.4  2066.5  2044.5  2049.0     7.2  2049.3  15095.0   
15  2015-12-09  2062.5  2079.5  2036.0  2042.0    16.6  2042.1  14066.0   
16  2015-12-08  2080.3  2080.9  2050.5  2058.7    22.3  2058.7   8948.0   
17  2015-12-07  2092.2  2095.2  2066.0  2081.5     7.4  2081.0   7312.0   
18  2015-12-04  2056.2  2092.5  2047.3  2087.7    37.2  2088.4  14848.0   
19  2015-12-03  2083.0  2095.2  2040.5  2051.5    30.4  2051.2  11325.0   
20  2015-12-02  2099.6  2104.8  2075.9  2081.8    18.3  2081.6   5226.0   
21  2015-12-01  2086.8  2101.0  2083.7  2100.0    20.1  2099.9   6022.0   
22  2015-11-30  2089.7  2094.9  2079.0  2082.7    10.1  2079.8   5400.0   
23  2015-11-27  2089.4  2097.9  2081.5  2089.8     1.8  2089.9   1481.0   
24  2015-11-25  2084.6  2092.1  2082.9  2087.8     3.4  2088.1   2256.0   
25  2015-11-24  2082.7  2091.0  2066.0  2084.8     0.5  2084.7   3909.0   
26  2015-11-23  2088.9  2092.8  2078.8  2084.0     4.5  2084.2   1868.0   
27  2015-11-20  2077.1  2094.0  2076.4  2088.5     9.5  2088.7   4871.0   
28  2015-11-19  2078.0  2089.2  2075.2  2079.0     0.5  2079.2   6995.0   
29  2015-11-18  2048.7  2082.0  2043.3  2080.0    30.7  2079.7   6941.0   
..         ...     ...     ...     ...     ...     ...     ...      ...   
371 2014-07-14  1962.9  1974.0  1962.7  1971.2     8.6  1971.0   5662.0   
372 2014-07-11  1956.6  1963.5  1953.0  1962.3     4.6  1962.4   4305.0   
373 2014-07-10  1968.0  1968.3  1945.5  1957.8     9.4  1957.8   6418.0   
374 2014-07-09  1960.2  1968.2  1958.7  1967.2     6.8  1967.2   4419.0   
375 2014-07-08  1970.4  1970.5  1953.0  1960.2    10.6  1960.4   5071.0   
376 2014-07-07  1976.4  1977.2  1967.3  1971.3     6.6  1971.0   2144.0   
377 2014-07-03  1967.5  1978.3  1966.3  1977.7     9.9  1977.6   3616.0   
378 2014-07-02  1966.8  1969.7  1965.0  1967.7     1.9  1967.7   3102.0   
379 2014-07-01  1954.7  1971.5  1953.8  1965.8    13.4  1965.8   4476.0   
380 2014-06-30  1952.0  1956.3  1948.1  1954.2     0.4  1952.4   4154.0   
381 2014-06-27  1948.3  1953.5  1943.2  1952.0     3.3  1952.0   3278.0   
382 2014-06-26  1948.6  1950.7  1936.0  1948.8     0.7  1948.7   4440.0   
383 2014-06-25  1942.8  1953.0  1937.5  1949.3     6.2  1949.4   5228.0   
384 2014-06-24  1951.3  1959.8  1940.0  1943.2     9.8  1943.2   3914.0   
385 2014-06-23  1952.6  1959.5  1950.2  1953.0     0.2  1953.0   3840.0   
386 2014-06-20  1949.0  1955.5  1948.5  1953.3     2.9  1953.2   6489.0   
387 2014-06-19  1958.0  1959.5  1954.0  1959.0     1.5  1958.5   9073.0   
388 2014-06-18  1942.5  1957.5  1939.0  1956.8    15.4  1957.0  16869.0   
389 2014-06-17  1933.3  1942.5  1932.2  1942.0     5.0  1941.6  39164.0   
390 2014-06-16  1933.0  1940.3  1931.0  1936.2     0.9  1936.6  39356.0   
391 2014-06-13  1933.5  1936.8  1927.5  1935.5     5.2  1935.7  20874.0   
392 2014-06-12  1943.8  1947.4  192