In [1]:
#08.Numpy-1

In [6]:
#Array with Python Lists
v = [0.5,0.75,1.0,1.5,2.0]
m = [v,v,v]
print(m)
print(m[1])
print(m[1][0])

[[0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0]]
[0.5, 0.75, 1.0, 1.5, 2.0]
0.5


In [9]:
v1 = [0.5,1.5]
v2 = [1,2]
m = [v1,v2]
c = [m,m]
print(c)
print(c[1][1][0])

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]
1


In [10]:
v = [0.5,0.75,1.0,1.5,2.0]
m = [v,v,v]
print(m)

[[0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0]]


In [12]:
v[0] = 'python'
print(m)

[['python', 0.75, 1.0, 1.5, 2.0], ['python', 0.75, 1.0, 1.5, 2.0], ['python', 0.75, 1.0, 1.5, 2.0]]


In [19]:
from copy import deepcopy
v = [0.5,0.75,1.0,1.5,2.0]
m = 3 * [deepcopy(v)]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [24]:
v[0] = 'python'
print(v)
print(m)

['python', 0.75, 1.0, 1.5, 2.0]
[[0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0]]


In [25]:
#python array class
v = [0.5,0.75,1.0,1.5,2.0]
import array
a = array.array('f',v)
print(a)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])


In [26]:
a.append(0.5)
print(a)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])


In [27]:
a.extend([5.0,6.75])
print(a)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])


In [28]:
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [30]:
# a.append('string') 不可添加与之前宣告的形态不一样的东西

In [34]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [41]:
#storege
f = open('array.apy','wb') # write binary
a.tofile(f) #a写入文件file
f.close()

In [43]:
with open('array.apy','wb') as f:
    a.tofile(f)

In [44]:
!dir arr*

 驱动器 C 中的卷没有标签。
 卷的序列号是 340F-4C0D

 C:\Users\Carol\Documents\jupyterLab\Chenghsi Hsieh\python for finance 的目录

2019/09/24  21:29                32 array.apy
               1 个文件             32 字节
               0 个目录 42,503,938,048 可用字节


In [45]:
b = array.array('f')
with open('array.apy','rb') as f:
    b.fromfile(f,5) #从f文件中抓5个元素出来
print(b)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])


In [51]:
b = array.array('d')
with open('array.apy','rb') as f:
    b.fromfile(f,4)
    print(b)

array('d', [0.0004882813645963324, 0.12500002956949174, 3.0517585400957614e-05, 24576.003944396973])


In [52]:
#Regular Numpy Arrays

In [55]:
import numpy as np
a = np.array([0.5,0.75,1.0,1.5,2.0])
print(a)
print(type(a))

[0.5  0.75 1.   1.5  2.  ]
<class 'numpy.ndarray'>


In [59]:
a = np.array(['a','b','c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [60]:
a = np.array(['aa','b','c'])
a

array(['aa', 'b', 'c'], dtype='<U2')

In [62]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
a = np.arange(8,dtype=np.float)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [70]:
print(a[:5])
print(a[5:])
print(a.sum())
print(a.std())
print(a.cumsum())

[0. 1. 2. 3. 4.]
[5. 6. 7.]
28.0
2.29128784747792
[ 0.  1.  3.  6. 10. 15. 21. 28.]


In [72]:
l = [0.,0.5,1.5,3.,5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [73]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [74]:
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [75]:
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [76]:
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [77]:
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [78]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [79]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [80]:
np.sqrt(2.5)

1.5811388300841898

In [81]:
import math
math.sqrt(2.5)
#math 不可向量化运算

1.5811388300841898

In [84]:
%timeit np.sqrt(2.5)

776 ns ± 33.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [85]:
%timeit math.sqrt(2.5)

163 ns ± 5.03 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [86]:
#multiple dimensions
b = np.array([a,a * 2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [87]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [88]:
b[0,2]

2.0

In [89]:
b[:,2]

array([2., 4.])

In [181]:
b[:,1:2]

array([[1.],
       [2.]])

In [90]:
b.sum()

84.0

In [92]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [93]:
b.sum(axis=1)

array([28., 56.])

In [95]:
c = np.zeros((2,3),dtype = 'i',order = 'C') 
#order C 电脑按行记录，order F 电脑按列记录
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [97]:
c = np.ones((2,3,4),dtype = 'i',order = 'C') 
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [103]:
d = np.zeros_like(c,dtype = 'f8',order = 'C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [104]:
d = np.ones_like(c,dtype = 'f8',order = 'C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [151]:
e = np.empty((2,3,2))
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [159]:
f = np.empty_like(c)
f

array([[[-929141224,        590,         50,          0],
        [         0,          0,          0,          0],
        [         0,          0, 1852990827, 1697541221]],

       [[1717713205,  758604852, 1684104546,  842609709],
        [ 895561017,  825057848,  909206577, 1647588962],
        [ 775434289, 1952543859, 1664250741,  825452088]]], dtype=int32)

In [161]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [165]:
g = np.linspace(5,15,11)
g

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [166]:
g = np.linspace(5,15,12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [167]:
#Meta-Information
g.size

12

In [170]:
g.itemsize #每一个字符用了几个bytes

8

In [172]:
g.ndim #张量维度

1

In [173]:
g.shape #向量维度

(12,)

In [175]:
g.dtype #预设float64

dtype('float64')

In [177]:
g.nbytes #total number of bytes in memory

96