In [1]:
#09.numpy-2

In [3]:
# Reshaping,Resizing,Stacking,Flattening
import numpy as np
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
print(g.shape)
print(np.shape(g))
print(g.ndim)
print(np.ndim(g))

(15,)
(15,)
1
1


In [40]:
print(g.reshape(3,5))
h = g.reshape(5,3)
print(h)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [11]:
print(h.T)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [41]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [13]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.resize(g,(3,1))

array([[0],
       [1],
       [2]])

In [16]:
np.resize(g,(1,5))

array([[0, 1, 2, 3, 4]])

In [18]:
np.resize(g,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
np.resize(g,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [20]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
#np.concatenate
np.hstack((h,2 * h)) #horizon 叠起来

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [24]:
np.vstack((h,0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [25]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
h.flatten(order = 'C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
h.flatten(order = 'F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [30]:
for i in h.flat:
    print(i,end = ',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [31]:
for i in h.flatten():
    print(i,end = ',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [33]:
for i in h.ravel(order = 'F'):
    print(i,end = ',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

In [34]:
for i in h.ravel(order = 'C'):
    print(i,end = ',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [35]:
# Boolean Arrays
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [36]:
h<8

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [43]:
h == 8

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [44]:
(h == 8).astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
(h > 4) & (h < 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [48]:
h[h > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
h[(h > 4) & (h < 12)]

array([ 5,  6,  7,  8,  9, 10, 11])

In [52]:
h[(h < 4) | (h > 12)]

array([ 0,  1,  2,  3, 13, 14])

In [53]:
np.where(h < 7,1,0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
np.where(h % 2,'even','odd')

array([['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd']], dtype='<U4')

In [55]:
np.where(h <= 7,h * 2,h / 2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [56]:
#Speed comparison
import random
I = 5000

In [57]:
%time mat = [[random.gauss(0,1) for j in range(I)] for i in range(I)]

Wall time: 20.6 s


In [63]:
mat[0][:6]

[1.70250381270478,
 1.7093580776659205,
 -1.0394332204996073,
 1.2733686008948604,
 1.9448010583270932,
 0.012459211550507662]

In [69]:
%time sum([sum(l) for l in mat])

Wall time: 159 ms


562.4030417717389

In [74]:
%time np.sum(mat)

Wall time: 46.9 ms


117.72814362668382

In [70]:
#用了多少个memory
import sys
sum([sys.getsizeof(l) for l in mat])

215200000

In [72]:
%time mat = np.random.standard_normal((I,I))

Wall time: 799 ms


In [73]:
%time np.sum(mat)

Wall time: 38.9 ms


117.72814362668382

In [75]:
mat.nbytes

200000000

In [76]:
sys.getsizeof(mat)

200000112

In [79]:
#Structure Array
dt = np.dtype([('Name','S10'),('Age','i4'),('Height','f'),('Children/Pets','i4',2)])
#Children里面有两个i4形态的资料
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [97]:
dt = np.dtype({'names':['Names','Age','Height','Children/Pets'],
              'formats':'O int float int,int'.split()})
dt

dtype([('Names', 'O'), ('Age', '<i4'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i4'), ('f1', '<i4')])])

In [103]:
s = np.array([('Smith',45,1.83,(0,1)),
              ('Jones',53,1.72,(2,2))])
print(s)
#print(s['Names']) 不可以

[['Smith' 45 1.83 (0, 1)]
 ['Jones' 53 1.72 (2, 2)]]


In [107]:
s = np.array([('Smith',45,1.83,(0,1)),
              ('Jones',53,1.72,(2,2))],dtype = dt)
print(s)
print(type(s))
print(s['Names'])
print(s['Height'].mean())
print(s[0])
print(s[1]['Age'])

[('Smith', 45, 1.83, (0, 1)) ('Jones', 53, 1.72, (2, 2))]
<class 'numpy.ndarray'>
['Smith' 'Jones']
1.775
('Smith', 45, 1.83, (0, 1))
53


In [110]:
#Vectorization of Code
np.random.seed(100)
r = np.arange(12).reshape(4,3)
s = np.arange(12).reshape(4,3) * 0.5

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]
 [4.5 5.  5.5]]


In [111]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [112]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [113]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [114]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [115]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [116]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [117]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [118]:
r.shape

(4, 3)

In [119]:
np.shape(r)

(4, 3)

In [121]:
s = np.arange(0,12,4)
s

array([0, 4, 8])

In [122]:
r + s #广播功能

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [124]:
s = np.arange(0,12,3)
s

array([0, 3, 6, 9])

In [127]:
#r + s 不可加
r.T + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [129]:
sr = s.reshape(-1,1) #允许一个轴数字不给出写作-1
sr

array([[0],
       [3],
       [6],
       [9]])

In [130]:
sr.shape

(4, 1)

In [131]:
r +s.reshape(-1,1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [133]:
def f(x):
    return 3 * x + 5

In [134]:
f(0.5)

6.5

In [135]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

In [6]:
#Memory Layout
x = np.random.standard_normal((100000,5))

In [7]:
y = 2 * x + 3

In [8]:
C = np.array((x,y), order = 'C')

In [9]:
C.shape

(2, 100000, 5)

In [10]:
F = np.array((x,y), order = 'F')

In [11]:
x = 0.0
y = 0.0
# freed up Memory

In [12]:
C[:2].round(2)#小数点取两位

array([[[ 0.35,  0.23,  0.18, -1.38,  0.23],
        [-1.59,  0.34,  1.68,  0.33, -1.41],
        [-0.49,  0.02,  0.55,  1.14,  1.3 ],
        ...,
        [ 0.32, -0.51,  0.13, -0.25, -1.97],
        [ 0.28, -1.02,  0.1 , -0.82,  0.69],
        [ 0.49, -1.  ,  1.11,  2.14,  0.11]],

       [[ 3.7 ,  3.46,  3.35,  0.24,  3.46],
        [-0.18,  3.69,  6.36,  3.65,  0.18],
        [ 2.02,  3.03,  4.1 ,  5.29,  5.59],
        ...,
        [ 3.64,  1.99,  3.25,  2.51, -0.93],
        [ 3.56,  0.95,  3.2 ,  1.35,  4.38],
        [ 3.97,  0.99,  5.22,  7.27,  3.23]]])

In [13]:
%timeit C.sum()

1.8 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit F.sum()

1.75 ms ± 153 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
%timeit C.sum(axis = 0)

4.51 ms ± 223 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
%timeit C.sum(axis = 0)

4.6 ms ± 123 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
%timeit C.sum(axis = 1)

4.17 ms ± 404 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit F.sum(axis = 0)

12 ms ± 371 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%timeit F.sum(axis = 1)

8.74 ms ± 251 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
