In [1]:
#20.Input Output Oprations-1

In [2]:
#Basic I/O with Python

In [3]:
#Writing Object To Disk

In [4]:
from pylab import plt,mpl
import pickle
import numpy as np
from random import gauss

In [5]:
a = [gauss(1.5,2) for i in range(1000000)]

In [6]:
!md data

子目录或文件 data 已经存在。


In [7]:
path = 'data/'

In [8]:
pkl_file = open(path + 'data.pkl','wb')

In [9]:
#pickle.dump() for writing objects
%time pickle.dump(a,pkl_file)

Wall time: 47.9 ms


In [10]:
pkl_file.close()

In [11]:
!dir data

 驱动器 C 中的卷没有标签。
 卷的序列号是 340F-4C0D

 C:\Users\Carol\Documents\jupyterLab\Chenghsi Hsieh\python for finance\data 的目录

2019/10/06  00:12    <DIR>          .
2019/10/06  00:12    <DIR>          ..
2019/10/06  00:00           569,294 data.csv
2019/10/06  00:12         9,002,006 data.pkl
2018/12/04  15:03           158,202 fxcm_eur_usd_eod_data.csv
2018/12/04  15:03        20,459,972 fxcm_eur_usd_tick_data.csv
2018/12/04  15:03           546,910 tr_eikon_aapl_tick.csv
2018/12/04  15:03           209,046 tr_eikon_eod_data.csv
2018/12/04  15:03           192,903 tr_eikon_eod_data_rounded.csv
2018/12/04  15:03             7,612 tr_eikon_option_data.csv
               8 个文件     31,145,945 字节
               2 个目录 44,430,094,336 可用字节


In [12]:
#读出来
pkl_file = open(path + 'data.pkl','rb')

In [13]:
%time b = pickle.load(pkl_file)

Wall time: 90.8 ms


In [14]:
a[:3]

[3.4811725352558867, -0.9739202102209394, 2.2251516089876753]

In [15]:
b[:3]

[3.4811725352558867, -0.9739202102209394, 2.2251516089876753]

In [16]:
#比较两个阵列是否完全相同
np.allclose(np.array(a),np.array(b))

True

In [17]:
pkl_file.close()

In [18]:
pkl_file = open(path + 'data.pkl','wb')

In [19]:
%time pickle.dump(np.array(a),pkl_file)

Wall time: 50.9 ms


In [20]:
%time pickle.dump(np.array(a) ** 2,pkl_file) 

Wall time: 57.8 ms


In [21]:
! dir data

 驱动器 C 中的卷没有标签。
 卷的序列号是 340F-4C0D

 C:\Users\Carol\Documents\jupyterLab\Chenghsi Hsieh\python for finance\data 的目录

2019/10/06  00:12    <DIR>          .
2019/10/06  00:12    <DIR>          ..
2019/10/06  00:00           569,294 data.csv
2019/10/06  00:12                 0 data.pkl
2018/12/04  15:03           158,202 fxcm_eur_usd_eod_data.csv
2018/12/04  15:03        20,459,972 fxcm_eur_usd_tick_data.csv
2018/12/04  15:03           546,910 tr_eikon_aapl_tick.csv
2018/12/04  15:03           209,046 tr_eikon_eod_data.csv
2018/12/04  15:03           192,903 tr_eikon_eod_data_rounded.csv
2018/12/04  15:03             7,612 tr_eikon_option_data.csv
               8 个文件     22,143,939 字节
               2 个目录 44,423,073,792 可用字节


In [22]:
#pickle store objects according to FIFO
pkl_file = open(path + 'data.pkl','rb')

In [23]:
x = pickle.load(pkl_file)
x[:4]

array([ 3.48117254, -0.97392021,  2.22515161,  2.58523155])

In [24]:
y = pickle.load(pkl_file)
y[:4]

array([12.11856222,  0.94852058,  4.95129968,  6.68342216])

In [25]:
pkl_file = open(path + 'data.pkl','wb')
pickle.dump({'x':x,'y':y},pkl_file)
pkl_file.close()

In [26]:
pkl_file = open(path + 'data.pkl','rb')
data = pickle.load(pkl_file)
pkl_file.close()

for key in data.keys():
    print(key,data[key][:4])

x [ 3.48117254 -0.97392021  2.22515161  2.58523155]
y [12.11856222  0.94852058  4.95129968  6.68342216]


In [27]:
!del data\data.pkl

In [28]:
!dir data

 驱动器 C 中的卷没有标签。
 卷的序列号是 340F-4C0D

 C:\Users\Carol\Documents\jupyterLab\Chenghsi Hsieh\python for finance\data 的目录

2019/10/06  00:12    <DIR>          .
2019/10/06  00:12    <DIR>          ..
2019/10/06  00:00           569,294 data.csv
2018/12/04  15:03           158,202 fxcm_eur_usd_eod_data.csv
2018/12/04  15:03        20,459,972 fxcm_eur_usd_tick_data.csv
2018/12/04  15:03           546,910 tr_eikon_aapl_tick.csv
2018/12/04  15:03           209,046 tr_eikon_eod_data.csv
2018/12/04  15:03           192,903 tr_eikon_eod_data_rounded.csv
2018/12/04  15:03             7,612 tr_eikon_option_data.csv
               7 个文件     22,143,939 字节
               2 个目录 44,439,097,344 可用字节


In [29]:
#Reading and Writing Text Files

In [30]:
import pandas as pd

In [31]:
rows = 5000
a = np.random.standard_normal((rows,5)).round(4)
a

array([[-0.1942, -0.356 , -0.7662, -0.2161, -0.3721],
       [ 0.1498,  1.6072, -1.4736,  0.9082,  0.5728],
       [-1.2113, -0.2479, -1.4994, -1.9336,  1.309 ],
       ...,
       [-0.862 , -0.524 , -0.604 ,  0.7291,  0.9832],
       [ 0.7868, -0.7907,  0.9758,  0.7117,  1.6583],
       [-1.9663,  1.4499, -0.9167,  1.3908, -0.7676]])

In [32]:
t = pd.date_range(start='2009/1/1',periods=rows,freq='H')
t

DatetimeIndex(['2009-01-01 00:00:00', '2009-01-01 01:00:00',
               '2009-01-01 02:00:00', '2009-01-01 03:00:00',
               '2009-01-01 04:00:00', '2009-01-01 05:00:00',
               '2009-01-01 06:00:00', '2009-01-01 07:00:00',
               '2009-01-01 08:00:00', '2009-01-01 09:00:00',
               ...
               '2009-07-27 22:00:00', '2009-07-27 23:00:00',
               '2009-07-28 00:00:00', '2009-07-28 01:00:00',
               '2009-07-28 02:00:00', '2009-07-28 03:00:00',
               '2009-07-28 04:00:00', '2009-07-28 05:00:00',
               '2009-07-28 06:00:00', '2009-07-28 07:00:00'],
              dtype='datetime64[ns]', length=5000, freq='H')

In [33]:
csv_file = open(path + 'data.csv','w')

In [34]:
headers = 'data,no1,no2,no3,no4,no5\n'

In [35]:
csv_file.write(headers)

25

In [36]:
for t_,(no1,no2,no3,no4,no5) in zip(t,a):
    s = '{},{},{},{},{},{}\n'.format(t_,no1,no2,no3,no4,no5)
    csv_file.write(s)

In [37]:
csv_file.close()

In [38]:
!dir data

 驱动器 C 中的卷没有标签。
 卷的序列号是 340F-4C0D

 C:\Users\Carol\Documents\jupyterLab\Chenghsi Hsieh\python for finance\data 的目录

2019/10/06  00:12    <DIR>          .
2019/10/06  00:12    <DIR>          ..
2019/10/06  00:12           289,747 data.csv
2018/12/04  15:03           158,202 fxcm_eur_usd_eod_data.csv
2018/12/04  15:03        20,459,972 fxcm_eur_usd_tick_data.csv
2018/12/04  15:03           546,910 tr_eikon_aapl_tick.csv
2018/12/04  15:03           209,046 tr_eikon_eod_data.csv
2018/12/04  15:03           192,903 tr_eikon_eod_data_rounded.csv
2018/12/04  15:03             7,612 tr_eikon_option_data.csv
               7 个文件     21,864,392 字节
               2 个目录 44,439,797,760 可用字节


In [39]:
csv_file = open(path + 'data.csv','r')

In [40]:
csv_file.readline()

'data,no1,no2,no3,no4,no5\n'

In [41]:
csv_file.readline()

'2009-01-01 00:00:00,-0.1942,-0.356,-0.7662,-0.2161,-0.3721\n'

In [42]:
csv_file.readline()

'2009-01-01 01:00:00,0.1498,1.6072,-1.4736,0.9082,0.5728\n'

In [45]:
for i in range(5):
    print(csv_file.readline(),end='')

2009-01-01 07:00:00,-0.7965,1.3788,0.5962,-0.1228,-1.082
2009-01-01 08:00:00,0.6368,0.7945,0.2596,-0.8943,-0.4145
2009-01-01 09:00:00,1.3394,-0.9897,0.658,-0.6953,-2.3331
2009-01-01 10:00:00,-0.977,0.4262,-0.4777,0.072,0.2784
2009-01-01 11:00:00,-0.1108,-0.5172,-0.0114,0.4483,0.4617


In [46]:
csv_file.close()

In [47]:
csv_file = open(path + 'data.csv','r')

In [48]:
content = csv_file.readlines()

In [49]:
content[:5]

['data,no1,no2,no3,no4,no5\n',
 '2009-01-01 00:00:00,-0.1942,-0.356,-0.7662,-0.2161,-0.3721\n',
 '2009-01-01 01:00:00,0.1498,1.6072,-1.4736,0.9082,0.5728\n',
 '2009-01-01 02:00:00,-1.2113,-0.2479,-1.4994,-1.9336,1.309\n',
 '2009-01-01 03:00:00,-0.421,2.0131,0.0985,0.1507,1.011\n']

In [50]:
csv_file.close()

In [51]:
import csv

In [52]:
with open(path + 'data.csv','r') as f: # with open自动关闭
    csv_reader = csv.reader(f)
    lines = [line for line in csv_reader]

In [53]:
lines[:5]

[['data', 'no1', 'no2', 'no3', 'no4', 'no5'],
 ['2009-01-01 00:00:00', '-0.1942', '-0.356', '-0.7662', '-0.2161', '-0.3721'],
 ['2009-01-01 01:00:00', '0.1498', '1.6072', '-1.4736', '0.9082', '0.5728'],
 ['2009-01-01 02:00:00', '-1.2113', '-0.2479', '-1.4994', '-1.9336', '1.309'],
 ['2009-01-01 03:00:00', '-0.421', '2.0131', '0.0985', '0.1507', '1.011']]

In [55]:
with open(path + 'data.csv','r') as f: # with open自动关闭
    csv_reader = csv.DictReader(f)
    lines = [line for line in csv_reader]

In [57]:
lines[:3]

[OrderedDict([('data', '2009-01-01 00:00:00'),
              ('no1', '-0.1942'),
              ('no2', '-0.356'),
              ('no3', '-0.7662'),
              ('no4', '-0.2161'),
              ('no5', '-0.3721')]),
 OrderedDict([('data', '2009-01-01 01:00:00'),
              ('no1', '0.1498'),
              ('no2', '1.6072'),
              ('no3', '-1.4736'),
              ('no4', '0.9082'),
              ('no5', '0.5728')]),
 OrderedDict([('data', '2009-01-01 02:00:00'),
              ('no1', '-1.2113'),
              ('no2', '-0.2479'),
              ('no3', '-1.4994'),
              ('no4', '-1.9336'),
              ('no5', '1.309')])]

In [58]:
!del data\data.csv

In [60]:
!dir data

 驱动器 C 中的卷没有标签。
 卷的序列号是 340F-4C0D

 C:\Users\Carol\Documents\jupyterLab\Chenghsi Hsieh\python for finance\data 的目录

2019/10/06  00:22    <DIR>          .
2019/10/06  00:22    <DIR>          ..
2018/12/04  15:03           158,202 fxcm_eur_usd_eod_data.csv
2018/12/04  15:03        20,459,972 fxcm_eur_usd_tick_data.csv
2018/12/04  15:03           546,910 tr_eikon_aapl_tick.csv
2018/12/04  15:03           209,046 tr_eikon_eod_data.csv
2018/12/04  15:03           192,903 tr_eikon_eod_data_rounded.csv
2018/12/04  15:03             7,612 tr_eikon_option_data.csv
               6 个文件     21,574,645 字节
               2 个目录 44,410,970,112 可用字节
